don't take a `system` argument in `default.nix`
nix-community/fenix pull request #181
Opened 2024-11-26 19:56 UTC by CobaltCause

Just one `system` is insufficient for cross compilation, although I'm not sure cross compilation is a concern for fenix.

Either way, nixpkgs' default behavior is good enough, and if callers need to do special things about systems, they can do so by providing an instance of nixpkgs configured the way they need it to be.

Also, I did some archeology and didn't find any specific rationale for the original choices:

* https://github.com/nix-community/fenix/pull/28/commits/c6eba37e469ed12c12eff8850831cb5784c385b9
* https://github.com/nix-community/fenix/commit/3d98d48fe91763dfc380f635da9c13de449dd509

2024-11-26 22:47 UTC, getchoo requested changes
I don't think there's any good reason for this change

> if callers need to do special things about systems, they can do so by providing an instance of nixpkgs configured the way they need it to be.

As while this is true, it makes things very tedious. The `--system` argument will no longer work for example, and it will much more annoying to build for specific systems on machines that support multiple (i.e., Apple silicon and x86_64/aarch64-darwin).

The only thing this PR does is remove that convenience in order to...save a few characters? 🫤

2024-11-27 05:35 UTC, CobaltCause commented
> The only thing this PR does is remove that convenience in order to...save a few characters? 🫤

The goal is to prevent fenix from calling `builtins.currentSystem` when it doesn't need to. Currently, this change isn't strictly necessary to get that behavior, because nix evaluation is lazy and fenix only uses `system` to instantiate nixpkgs, which can be overriden. This could be a problem if fenix began reading the `system` parameter directly elsewhere in its code, though, and that would make for an extra thing to override to avoid referencing `builtins.currentSystem`.

2024-11-27 06:30 UTC, CobaltCause commented
> The `--system` argument will no longer work for example.

Hmm, I don't think this is true. In my testing, this directly affects the value given by `builtins.currentSystem`, and does not rely on the nix expression taking arguments taking `system`:

`foo.nix`:
```
{
  pkgs ? import <nixpkgs> {},
}:

{
  foo = builtins.currentSystem;
}
```
```console
$ nix eval --system foo --impure --expr '(import ./foo.nix {}).foo'
"foo"
```

2024-12-01 01:02 UTC, getchoo commented
Ah TIL. I thought it was always shorthand for `--argstr system` since I had actually had some issues with it working before

Regardless though, this is still removing convivence in other areas (like importing things directly), straying from (mostly) standard practice, and breaking API compatibility for something that isn't actually an issue right now. If you *really* want to be proactive about preventing the use of this binding elsewhere, a better solution would probably be to shadow it with a new `system` binding in a top level `let ...; in` expression

i.e.
```nix
{
  pkgs ? import (getFlake "nixpkgs") { localSystem = { inherit system; }; },
  system ? currentSystem
}:

let
  inherit (pkgs.stdenv.hostPlatform) system;
in
```

2024-12-10 18:59 UTC, closed without merging