simplify non-flake usage
nix-community/fenix pull request #28
Opened 2021-08-26 21:33 UTC by zimbatm

This change breaks backward-compatibility.

* package.nix becomes default.nix
* overlay.nix disappears. Build your own overlay if you don't use
  flakes.
* replace flake-compat with flake.lock.nix that just tries to pull the
  dependencies from the lockfile.

This brings back the convention that default.nix holds all of the
packages. The main advantage is that non-flake users can now also pass
their own versions of everything to the constructore. A secondary
advantage is that `nix repl .` works and makes it easier to debug. A
third smaller advantage is that the flake.nix is now properly lean.

Related to https://github.com/nix-community/nixpkgs-fmt/issues/257 where I
noticed that the flake is itself loading flake-compat.

2021-08-28 03:17 UTC, figsoda requested changes
it would be better if `default.nix` is more `callPackage` friendly

2021-08-28 03:17 UTC, figsoda commented on default.nix
> +with lib;
This should be able to replace `flake.lock.nix`, also I don't think flakeLock should be an argument here
```suggestion
with builtins;

let
  getFlake = name:
    with (fromJSON (readFile ./flake.lock)).nodes.${name}.locked;
    fetchTarball {
      url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
      sha256 = narHash;
    };

in { system ? currentSystem
, nixpkgs ? import (getFlake "nixpkgs") { inherit system; }, lib ? nixpkgs.lib
, rust-analyzer-src ? getFlake "rust-analyzer-src" }:

with lib;

```

2021-08-28 03:17 UTC, figsoda commented on flake.nix
> +    packages = builtins.mapAttrs (system: _:
use [`genAttrs`](https://github.com/nixos/nixpkgs/blob/3f4ce46a4702940cb7d1d12349c0407576225605/lib/attrsets.nix#L100-L107)

2021-08-28 11:12 UTC, zimbatm commented
the history needs to be squashed but I wanted to keep the changes apparent for now

2021-08-28 21:11 UTC, figsoda commented
Changing from `packages` to `legacyPackages` would basically break it for everybody. There are other ways of addressing this (e.g. making `complete` an alias to `complete.toolchain`) and failing `nix flake check` is not a big issue and can be addressed in another pr.

2021-08-29 14:19 UTC, zimbatm commented
yeah. I'll revert that last commit because there is no way to keep the current structure and be `flake check` compatible.

2021-08-29 15:45 UTC, merged